### PR TITLE
Add My Classes page with enhanced class management features

### PR DESCRIPTION
**Pull request by Pmacdon15**
This pull request introduces a new "My Classes" page, allowing users to view, add, and drop classes. It includes a seasonal filtering feature for class selection and improves data handling by loading class information from local storage. The code has been refactored for better readability, and unnecessary functions have been removed. Additionally, the user interface has been styled for a more cohesive experience. Overall, this update enhances the user experience by providing a more intuitive way to manage classes.

### CODE REVIEW

**Comment by Pmacdon15** [comment]
# My Classes Page
# Added:
- student-portal-my-classes:email
- DisplayAvailabeClasses.component
- DisplayUserClasses.component
## Changed:
- All classes data is now stored locally
- User Classes data is now stored locally
- Function to add class to user classes
- Function to remove user classes
## Functionally:
- User can pick term based on current term
- User can pick a first term when they have no classes registered 
-  Users can add class
- Users can drop class

> REQUEST
> Please test this branch before merging to check for bugs.
## View my branch:
- You can check out my branch at [12-needed-my-classes-page](https://github.com/Pmacdon15/final_project_web/tree/12-needed-my-classes-page)
- Fetch the repo again and check out the branch called ```12-needed-my-classes-page``` using vs code.
-  Or in your terminal by going to the project folder and typing:
```bash
git fetch origin
git checkout 12-needed-my-classes-page
```
Then starting the project up and going to:```localhost:3000/student-portal-my-classes/:email```
## Images:
MyClassesSkinnyNoClasses
MyClassesSkinny
MyClassesAvaUserClass

@thiagolima19 @manufflopes @mariannaAntunes Hey guys!! This is my progress for the night. No Pr to review yet.

**Comment by thiagolima19** [comment]
- Course Registration: Students can register for 2-5 courses per term and can’t register for the same course twice in the same term.
- The user class can't be dropped; only the available ones can be dropped. 
- if I click in term 2 and try to drop the course I return to term 1 and do not drop it
- every time I add a course it returns to term 1 instead of staying in term 2
- if I am in term 3 and add a course it is enabling the button for term 4 to appear

**Comment by Pmacdon15** [comment]
# Updated 
- Fixed Empty term bug
- Fixed remove term bug
- Changed css to suggested layout
- Css is responsive
 # Images 
new css skinny
new css wide
 
@thiagolima19 Please review branch and code, its ready for approval.

**Review by thiagolima19 — APPROVED** [review]
great!!

**Pull request merged**
